const courses = [
  {
    id: "c1",
    courseCode: "ITCS495",
    courseName: "Special Topics in Databases and Intelligent Systems",
    competencyTags: [
      "Machine Learning Fundamentals",
      "Feature Engineering",
      "Model Evaluation",
      "Data Storytelling",
      "Experiment Design",
      "Team Collaboration",
    ],
    relevancePercent: 90,
    grade: "A",
    visibleTo: ["u1", "u2", "u3"],
  },
  {
    id: "c2",
    courseCode: "ITCS212",
    courseName: "Web Programming",
    competencyTags: ["JavaScript", "REST API Integration", "Frontend Development"],
    relevancePercent: 60,
    grade: "B+",
    visibleTo: ["u1", "u2", "u3"],
  },
  {
    id: "c3",
    courseCode: "ITCS241",
    courseName: "Database Management Systems",
    competencyTags: ["SQL", "Database Design"],
    relevancePercent: 85,
    grade: "A",
    visibleTo: ["u1", "u2", "u3"],
  },
  {
    id: "c4",
    courseCode: "ITCS227",
    courseName: "Introduction to Data Science",
    competencyTags: [
      "Data Analysis",
      "Statistics",
      "Python",
      "Machine Learning Basics",
      "Data Visualization",
      "Data Cleaning",
    ],
    relevancePercent: 82,
    grade: "A-",
    visibleTo: ["u1", "u2", "u3"],
  },
  {
    id: "c5",
    courseCode: "ITCS348",
    courseName: "Introduction to Natural Language Processing",
    competencyTags: [
      "NLP",
      "Text Processing",
      "Python",
      "Machine Learning",
      "Language Models",
      "Information Retrieval",
    ],
    relevancePercent: 88,
    grade: "A",
    visibleTo: ["u1", "u2", "u3"],
  },
];

export default courses;
